Updates deprecated node installation method
bids-apps/base_validator pull request #11
Opened 2023-10-30 00:29 UTC by lamoglia

2023-11-06 11:35 UTC, Remi-Gau commented
We use neurodocker to generate the dockerfile: preferable to modify the makefile in this case

2023-11-06 11:37 UTC, Remi-Gau commented
Will have a look at more details in what you suggest to check what can be added to it.

Note that I also opened an issue on neurodocker repo to facilitate installing the bids validator in any docker recipe, so I probably should try to reuse your suggestion in this other repo.

2023-11-06 11:57 UTC, Remi-Gau commented
Note to myself:
- circle CI should run on PRs

2023-11-08 12:26 UTC, Remi-Gau commented on Dockerfile
> +ENV NODE_MAJOR 18
```suggestion
ENV NODE_MAJOR 18 
```

2023-11-08 12:27 UTC, Remi-Gau commented on Dockerfile
> +ENV NODE_MAJOR 18
dummy change to see if circle ci runs

2023-11-08 12:35 UTC, Remi-Gau commented on Dockerfile
> +RUN mkdir -p /etc/apt/keyrings
```suggestion
RUN mkdir -p /etc/apt/keyrings 
```

2023-11-08 16:56 UTC, Remi-Gau requested changes
yup the changes make sense to me

just better to transfer those changes into the makefile: https://github.com/bids-apps/base_validator/blob/master/Makefile

and then let neurodocker take care of writing the dockerfile and the extra boilerplate

let me know if you need pointers on how to do that

2023-11-08 17:07 UTC, lamoglia commented
Ok, will do.

2023-11-09 13:53 UTC, closed without merging